name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./Booking.Server
      run: dotnet restore
    - name: Build
      working-directory: ./Booking.Server
      run: dotnet publish --no-restore --output artifacts
    - name: Test
      working-directory: ./Booking.Server
      run: dotnet test --no-build
    - name: copy artifacts
      run: mkdir art && cp -r ./Booking.Server/artifacts/* Dockerfile art
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./art
  
  docker:
    needs: build
    name: publish to dockerhub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/booking-api_github:latest
